# Generated by Django 4.1 on 2022-08-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('user', 'User'), ('Staff', 'Staff'), ('Manager', 'Manager')], default=None, max_length=50),
        ),
    ]
