# Generated by Django 4.1 on 2022-08-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('General', 'General'), ('Staff', 'Staff'), ('Manager', 'Manager')], default=None, max_length=50),
        ),
    ]
