# Generated by Django 4.1 on 2022-08-18 22:17

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_profile_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='acc_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='start_date',
            field=models.DateField(),
        ),
    ]
