# Generated by Django 4.1 on 2022-08-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeecontract_acc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.jobposition'),
        ),
    ]
