# Generated by Django 4.1 on 2022-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employeecontract_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.CharField(max_length=200),
        ),
    ]
