# Generated by Django 4.1 on 2022-08-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='users',
            new_name='user',
        ),
    ]
