# Generated by Django 4.1 on 2022-08-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_emergency_contact_employee_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
