# Generated by Django 4.1 on 2022-08-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
