# Generated by Django 4.1 on 2022-08-31 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
