# Generated by Django 4.1 on 2022-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_remove_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='badge_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pix'),
        ),
    ]
