# Generated by Django 4.1 on 2022-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_remove_employee_badge_id_alter_employee_profile_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('General', 'General'), ('Staff', 'Staff'), ('Manager', 'Manager')], max_length=50),
        ),
    ]
