# Generated by Django 4.1 on 2022-09-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='badge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
