# Generated by Django 4.1 on 2022-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_employee_dept_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='contract_reference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
