# Generated by Django 4.1 on 2022-09-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontract',
            name='acc_no',
        ),
    ]
