# Generated by Django 4.1 on 2022-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_remove_employeecontract_acc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='acc_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
